# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        AppBundle\Entity\Membre: 'bcrypt'


    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        #in_memory:
        #    memory:
        #        users:
        #            nassim:
        #                password: 123456
        #                roles: 'ROLE_USER'
        
        #            admin:
        #                password: admin
        #                roles: 'ROLE_ADMIN'

        poles_provider: 
            entity:
                class: AppBundle:Membre
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html

            form_login: 
                login_path: connexion
                check_path: connexion_check
                default_target_path: homepage

            logout: 
                path: deconnexion
                target: homepage

    access_control:
        - { path: ^/connexion, allow_if: "not has_role('ROLE_USER')" }
        - { path: ^/inscription, allow_if: "not has_role('ROLE_USER')" }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profil, roles: ROLE_USER }
        - { path: ^/admin/stats, roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin/compta, roles: ROLE_COMPTA }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_COMPTA: ROLE_ADMIN
        ROLE_SPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_COMPTA]
        